### ISSUE TITLE
Monstra rebranded to Flextype!

### ISSUE THREAD

**Issue by Awilum** [monstra-cms/monstra#448]
**Dear Friends and Monstra Followers!**
**I need to inform you about _big infrastructure changes._**

**Project Monstra was rebranded to Flextype! 
That is means that _project Monstra will not supported any more!_ 
I am working on a new project called Flextype!** 

**Flextype** is Open Source, fast and flexible file-based Content Management System. That's Easy to install, upgrade and use. Flextype provides amazing API's for plugins, themes and core developers! Content in Flextype is just a simple files written with markdown syntax in pages folder. You simply create markdown files in the pages folder and that becomes a page.

#### Simple
Easy to install, upgrade and use.  
No installation needed, just copy files to your server!  

#### Fast
Flextype is realy fast and lightweight!  
No database required, flat files only!  

#### Flexible
Flextype provides amazing API for plugins, themes and core developers!  

#### Markdown Syntax
Use your favorite editor to write your content with plain Markdown syntax.  

#### Dynamic Content Types
The flat-file nature of Flextype lets you define custom fields for any of your pages.  

#### Open Source
Flextype is an open-source project licensed under the MIT LICENSE to set the world free!  

## REQUIREMENTS
PHP 7.1.3 or higher with PHP's [Multibyte String module](http://php.net/mbstring)   
Apache with [Mod Rewrite](http://httpd.apache.org/docs/current/mod/mod_rewrite.html)  

#### Using (S)FTP

[Download the latest version.](http://flextype.org/download)  

Unzip the contents to a new folder on your local computer, and upload to your webhost using the (S)FTP client of your choice. After you’ve done this, be sure to chmod the following directories (with containing files) to 777, so they are readable and writable by Flextype:  
* `site/`

#### Using Composer

You can easily install Flextype with Composer.

```
composer create-project flextype/flextype
```

Also you may need to install node_modules libs for default Simple Theme  

```
cd /flextype/site/themes/simple  
npm install
gulp
```

## COMMUNITY
Flextype is open source, community driven project, and maintained by community!

* [Forum](http://forum.flextype.org)
* [Github Repository](https://github.com/flextype/flextype)
* [Gitter](https://gitter.im/flextype/flextype)

## NO LIMITS
With Flextype you can create any project you whant.

* Business site
* Landing page
* Personal site
* Portfolio
* Product site
* Documentation
* Personal resume
* Blog

## CONTRIBUTE
Flextype is an open source project and community contributions are essential to its growing and success. Contributing to the Flextype is easy and you can give as little or as much time as you want.   
* Help on the [Forum.](http://forum.flextype.org)
* Develop a new plugin.
* Create a new theme.
* Find and [report issues.](https://github.com/flextype/flextype/issues)
* Link back to [Flextype](http://flextype.org).
* [Donate to keep Flextype free.](http://flextype.org/about/sponsors)

## LINKS
- [Site](http://flextype.org)
- [Forum](http://forum.flextype.org)
- [Documentation](http://flextype.org/documentation)

## LICENSE
See [LICENSE](https://github.com/flextype/flextype/blob/master/LICENSE.md)

**If you not agree about getting notifications from GitHub about project update, please unfollow it.**

**Comment by Awilum** [comment]
@morfej @leMonstraDev @i-do @mhaidarh @linuxjuggler @skz169 @xqsapper @k0nsl @doolab @glebcha @postprefix @ryu-blacknd @aaronarich @jianyuan @rnsk @savage69kr @paweljonik @TomiToivio @vyspiansky @warprobot @sakarya @yvmarques @OSC-CMS @alixaxel @giobautista @huanghua581 @andrewminton @tibounise @dmitrymomot @sandrobilbeisi

**Comment by Awilum** [comment]
@dimakniga @justadm @ruromanus @markusthomasde @joshmedeski @robsalasco @corona6 @AZJacky @vkudrik @pateljj04 @reinaldodiazlugo @r0bzem @EgorBulychev @gholm @Xmk @pafnuty @nook-ru @siko @crudbug @codedaiquiri @jiji262 @BeSublime @ofisia @AgtLucas @erickpatrick @richard-jpg @KEPZ @tigefa4u @thunder-spb @kopirat

**Comment by Awilum** [comment]
@kurtextrem @hizhengfu @iuranemo @micheldejoode @crabcz @vteixeira @twmbx @tovic @VladoMS @studio507 @superg2 @boyaq @nobody1986 @JaniL @imestny @Uewdl @bernte @dok2d @rajeshpillai @PedroFelipe @exnius @zoski @hhdem @iheanyi @merzak7 @tedor @dwichers @briefwriter @kenetik @ssundarraj

**Comment by Awilum** [comment]
@FizzyGiant @brentrobbins @metalgvc @yanguanglan @filipeoliveiraa @foo9 @gracix @zinkh @afonsomota @diogomoretti @xdevel @Maximwolker @Saturnych @frankcaron @chrise86 @vjandrei @Flipo @ilmsg @memakeit @chiqui3d @DarrylD @hoangtx @Riu @aixnr @ymouri @eugenf @jucke @billymail @vivekrp @thedeadofblackfire

**Comment by Awilum** [comment]
@aemidesign @7072656d @vanting @giftnuss @rosko @yamamotok @kalligator @effu @lifesign @keltstr @Martynoff @blurkness @townewgokgok @guyhughes @toby3d @freela @hunslater @ibahtin @StrangeFruit @bpmore @tomibiloglav @nibreh @archi-mobile @jkrayer @Maykl @ygauthier @mciszczon @ravilrrr @bigzebra @coldwinds

**Comment by Awilum** [comment]
@abecko @witoldgraca @migswd @andrewbowley @marktopper @codefucker @goliatone @astappev @eintnohick @IGitSylvia @cellfusion @gerundt @benjaminach @pbuzdin @dev1vitaly @zeriyu @syano @e-jigsaw @wachilt @Shuunen @snowdream @dennschu @selique @betaverse @mariusrugan @tlxyz @osmanzeki @serge-yefimov @tjaadvd @petitroto

**Comment by Awilum** [comment]
@fubira @mightyhaggis @impactracer @Krishan19 @andreebit @MelkyWay @auxonic @bianpratama @Freddynic159 @codev0 @andychups @ivanhercaz @murilocosta @TeddyBear06 @0x309 @codesundar @takeshi81 @jimwild @bede @tammifull @fokusov @tomothumb @klmcgregor @strseb @nmarulo @alekzonder @rascoop @changalberto @tbreuss @HerrHase

**Comment by jeanthom** [comment]
Please stop spam.

**Comment by Awilum** [comment]
@phocks @berteh @afbora @cyberwani @skamoen @xgenvn @ziyaddin @anhtuannguyentran @LostCore @ilyasamorodov @chrisdiana @margeeta @Torsten-K @palamida @polikin @remo1 @yozaira @bynicolas @HackerLabs @VinsVinnipuh @supaweb @takuan-osho @kevinkoosk @amitjindal @iamweird @szabcsee @memexx-com @aliceylan @cmwwebfx @milansw

**Comment by Awilum** [comment]
@wolfg1969 @muten84 @M0Rf30 @bhdzllr @robmind @kublaj @Jolg42 @Raiper34 @ferman @thoncs @nOttenga @fdisotto @dimayakovlev @Naser-SherafatiNia @vracas @macbernic @ishawge @Niko-r @dennykuo @airspace @ilakast @neoartdoo @wllkle @seajean @lesichkovm @pilagila @eabeta @AndreiDuma @stevenng @nikolay

**Comment by Awilum** [comment]
@berteh @afbora @cyberwani @skamoen @xgenvn @ziyaddin @anhtuannguyentran @LostCore @ilyasamorodov @chrisdiana @margeeta @Torsten-K @palamida @polikin @remo1 @yozaira @bynicolas @HackerLabs @VinsVinnipuh @supaweb @takuan-osho @kevinkoosk @amitjindal @iamweird @szabcsee @memexx-com @aliceylan @cmwwebfx @milansw @wolfg1969

**Comment by Awilum** [comment]
@muten84 @M0Rf30 @bhdzllr @robmind @kublaj @Jolg42 @Raiper34 @ferman @thoncs @nOttenga @fdisotto @dimayakovlev @Naser-SherafatiNia @vracas @macbernic @ishawge @Niko-r @dennykuo @airspace @ilakast @neoartdoo @wllkle @seajean @lesichkovm @pilagila @eabeta @AndreiDuma @stevenng @nikolay @vdanelia

**Comment by marktopper** [comment]
Do you have to spam?

**Comment by jeanthom** [comment]
Please stop SPAM.

**Comment by Awilum** [comment]
@marktopper As I see you follow Monstra Project. I am informing you about BIG PROJECT UPDATE - is it a problem ?

**Comment by marktopper** [comment]
Following the project means that we get a notification whenever an issue is created at Github's notification page. There is no need to tag everyone here, if people surely follow the repository, just make an issue about it and leave it there.
However, doing this could leave people to un-follow the repository instead.

**Comment by Awilum** [comment]
@marktopper Good Luck, Mark :)

**Comment by Kristories** [comment]
This is good news, and the author is happy to tell all contributors. I don't mind being mentioned (maybe spam), but not for some people.

I feel lucky to get this information, because there is no update since two years ago. Congratulation @Awilum - Flextype!

![](https://media.giphy.com/media/5GoVLqeAOo6PK/giphy.gif)

**Comment by Riu** [comment]
Sorry, but I need to say that - it's stupid action. This is wrong way to build community.

**Comment by tibounise** [comment]
Yep plain stupidity. I received like 20 mails related to this project.

**Comment by Ultrabenosaurus** [comment]
This is spam, plain and simple. I only Starred the repo so I could find it again in the future; I specifically did not Watch it so that I would not receive emails. 

I did not give you permission to email me for marketing purposes. In fact, I have not given you permission to email me at all, which is pretty critical now GDPR is in effect.

**Comment by Awilum** [comment]
@Ultrabenosaurus please unfollow project if you don’t want to recive notifications about its BIG INFRASTRUCTURE UPDATES

**Comment by Ultrabenosaurus** [comment]
This is a marketing update. You open by saying it was rebranded, no mention of other changes, and no comparison between the two versions in the entire post at the time I'm writing this. Do not lie about the purpose of the thread. I specifically did not Watch this repo and I was never asked for consent to be contacted for marketing. Any European citizen can report you for breaching GDPR for forced contact. It's not like I signed up to your newsletter or otherwise asked for updates, I only Starred the project in case I ever needed to self-host a CMS.

**Comment by Ultrabenosaurus** [comment]
Do you just delete comments you don't like?

This is a marketing update. You open by saying it was rebranded, no mention of other changes, and no comparison between the two versions in the entire post at the time I'm writing this. Do not lie about the purpose of the thread. I specifically did not Watch this repo and I was never asked for consent to be contacted for marketing. Any European citizen can report you for breaching GDPR for forced contact. It's not like I signed up to your newsletter or otherwise asked for updates, I only Starred the project in case I ever needed to self-host a CMS.

http://web.archive.org/web/20180609152854/https://github.com/monstra-cms/monstra/issues/448

**Comment by Ultrabenosaurus** [comment]
Do you just delete comments you don't like?

This is a marketing update. You open by saying it was rebranded, no mention of other changes, and no comparison between the two versions in the entire post at the time I'm writing this. Do not lie about the purpose of the thread. I specifically did not Watch this repo and I was never asked for consent to be contacted for marketing. Any European citizen can report you for breaching GDPR for forced contact. It's not like I signed up to your newsletter or otherwise asked for updates, I only Starred the project in case I ever needed to self-host a CMS.

http://web.archive.org/web/20180609152854/https://github.com/monstra-cms/monstra/issues/448

http://web.archive.org/web/20180609154107/https://github.com/monstra-cms/monstra/issues/448

**Comment by mariusrugan** [comment]
wow!
another russian that doesn't get what common sense is.

**Comment by Shuunen** [comment]
Deleting this kind of comments shows how you deal with other people ideas

**Comment by Awilum** [comment]
@Shuunen what is your question about ? did you read the issue ?

**Comment by Shuunen** [comment]
Why deleting people critics about your spamming behaviour ?

**Comment by Awilum** [comment]
@Shuunen please read the issue. you are flooding now, should I keep your comment here ?

**Comment by pbuzdin** [comment]
WTF stupid spam?!

**Comment by astappiev** [comment]
Please, forget me and never send such letters to me as well.
If I want to introduce a new project, use Product Hunt for that.

**Comment by Awilum** [comment]
@astappev seems you not read the issue. 
If you not agree about getting notifications from GitHub about project update, please unfollow it.
Thanks!

**Comment by ravilrrr** [comment]
Мне вот одного не понятно, откуда у людей столько желчи? Ну пришло лишних 10 писем и что теперь? Конец света? Пенисы прислали и дети прочитали? Деньги сняли? В чем проблема то??? Никогда спам не получали? Ну нужная информация... почему бы  не получить? Блин, будьте добрее.... развели проблему на пустом месте!!!!!
